Task creation for google calendar is done
shoaib2529/MeasureMe pull request #10
Opened 2022-06-02 10:17 UTC by Huzii-droid19

Google calendar task creation is completed, please review it.
moreover, RTK uses a base query to process requests, which doesn't allow to use of another base query. To make a custom query, we have to define basically two endpoints, one for addTaskToGoogle, and addTask.
As of now, i have done it with fetch API.

2022-06-02 10:53 UTC, shoaib2529 requested changes

2022-06-02 10:53 UTC, shoaib2529 commented on android/app/build.gradle
> +// apply plugin: 'com.google.gms.google-services' //
Remove Commented Code.

2022-06-02 10:53 UTC, shoaib2529 commented on android/app/build.gradle
> +    // implementation platform('com.google.firebase:firebase-bom:30.1.0') //
Remove

2022-06-02 10:53 UTC, shoaib2529 commented on android/build.gradle
> +        // classpath("com.android.tools.build:gradle:7.0.4")
Remove

2022-06-02 10:53 UTC, shoaib2529 commented on src/screens/newtask/index.tsx
> +  console.log(GOOGLE_CLIENT_ID);
Remove Console Logs

2022-06-02 10:53 UTC, shoaib2529 commented on src/screens/newtask/index.tsx
> +      }
Write more efficient Code.
`if(checked)
await handleSignIn();
await createTask();
`

Above code is enough for try block.

2022-06-02 10:53 UTC, shoaib2529 commented on src/store/api/index.ts
> +  fetch(GOOGEL_CALENDAR_BASE_URL, {
Why Fetch?

2022-06-02 12:24 UTC, Huzii-droid19 commented on src/store/api/index.ts
> +  fetch(GOOGEL_CALENDAR_BASE_URL, {
we have to define a custom endpoint, where first it adds a task to google calendar, then adds it to mock API,
and simple add task will also be present there.
OR
we could pass a 'checked' variable as an argument to custom base query, and execute query accordingly

2022-06-03 05:26 UTC, Huzii-droid19 commented on src/store/api/index.ts
> +  fetch(GOOGEL_CALENDAR_BASE_URL, {
Updated: Used RTK for it.

2022-06-03 05:30 UTC, shoaib2529 requested changes

2022-06-03 05:30 UTC, shoaib2529 commented on src/index.tsx
> +import * as R from 'ramda';
Why not import just the required function instead of whole library?

2022-06-03 05:30 UTC, shoaib2529 commented on src/screens/newtask/index.tsx
> +          description: description,
You can just type as 
`description,`
instead of 
`description:description,`

2022-06-03 05:30 UTC, shoaib2529 commented on src/screens/newtask/index.tsx
> +        accessToken: accessToken,
Same
`accessToken,`

2022-06-03 05:34 UTC, Huzii-droid19 commented on src/index.tsx
> +import * as R from 'ramda';
done

2022-06-03 05:34 UTC, Huzii-droid19 commented on src/screens/newtask/index.tsx
> +          description: description,
done

2022-06-03 05:34 UTC, Huzii-droid19 commented on src/screens/newtask/index.tsx
> +        accessToken: accessToken,
done

2022-06-03 10:36 UTC, merged